name: Deploy Node.js to Staging (EC2)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: main-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure backend folder permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}/backend
            sudo chown -R $USER:$USER /home/${{ secrets.EC2_USER }}/backend
            sudo chmod -R u+rwX /home/${{ secrets.EC2_USER }}/backend

      - name: Upload project to EC2 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: .
          target: /home/${{ secrets.EC2_USER }}/backend
          overwrite: true

      - name: Deploy Node.js App on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            cd /home/${{ secrets.EC2_USER }}/backend

            echo "Current directory: $(pwd)"
            echo "Files in current directory:"
            ls -la

            # Install Node.js 18 if not installed
            if ! command -v node &> /dev/null; then
              echo "Installing Node.js 18..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Install PM2 if not installed
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              sudo npm install -g pm2
            fi

            # Install dependencies
            echo "Installing dependencies..."
            npm install --production

            # Build the project if build script exists
            if [ -f "package.json" ] && grep -q "\"build\"" package.json; then
              echo "Running npm run build..."
              npm run build
            fi

            # Stop running PM2 instance
            echo "Stopping existing PM2 app..."
            pm2 stop backend-app || true
            pm2 delete backend-app || true

            # Start new PM2 instance
            echo "Starting Node.js backend with PM2..."
            pm2 start server.js --name backend-app

            # Save PM2 startup so it restarts after reboot
            pm2 save
            pm2 startup systemd -u $USER --hp /home/$USER

            echo "Deployment completed!"
